edition = "2024"
style_edition = "2024"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
unstable_features = true
use_field_init_shorthand = true
